//unKnown Exception
main() {
  try {
    int div=5~/0;
    print(div);
  } catch (e) {
  }
  finally {
    print("This Statement Always Executed");
  }
  int num = 2 * 3;
  print(num);
}
